	AREA RESET, DATA, READONLY
	EXPORT __Vectors

__Vectors
	DCD 0x10000000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R0,= SRC
	LDR R1,= DST	
	LDR R2, [R0], #4
	LDR R3, [R0]
	SUBS R4, R2, R3
	STR R4, [R1]
	
SRC DCD 0x12345678, 0x9ABCDEF0
	AREA DATASEG, DATA, READWRITE
DST DCD 0
	END